spring.application.name=PCConfigurator

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/pc_configurator
spring.datasource.username=postgres
spring.datasource.password=dimash666
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

spring.flyway.baseline-on-migrate=false

