create table components(

    id int generated by default as  identity not null,

    name varchar(255) not null,
    price double precision not null,
    category VARCHAR(31) NOT NULL,

    primary key(id)
);

create table cpu(

    id int not null,

    socket varchar(50) not null ,

    tdp int not null,

    primary key (id),

    foreign key (id) references components(id) ON DELETE CASCADE

);

create table pc_case(

    id int not null,

    supported_form_factors varchar(50) not null,

    max_gpu_length int not null ,

    max_cooler_height int  not null,

    primary key (id),

    foreign key (id) references components(id) ON DELETE CASCADE

);

create table gpu(

    id int not null,

    power_consumption int not null,

    power_connectors varchar(50) not null,

    length_gpu int not null,

    primary key (id),

    foreign key (id) references components(id) ON DELETE CASCADE

);


create table motherboard(

    id int not null,

    socket varchar(50) not null,

    ram_type varchar not null,

    form_factor varchar(50) not null,

    primary key (id),

    foreign key (id) references components(id) ON DELETE CASCADE

);

create table cooler(

    id int not null,

    supported_sockets varchar(50) not null,

    max_tdp int not null,

    height_cooler int not null,

    primary key (id),

    foreign key (id) references components(id) ON DELETE CASCADE

);

create table ram(

    id int not null,

    memory int not null,

    type_ram varchar(50) not null,

    primary key (id),

    foreign key (id) references components(id) ON DELETE CASCADE

);

create table psu(

    id int not null,

    total_power int not null,

    available_connectors varchar(50) not null,

    primary key (id),

    foreign key (id) references components(id) ON DELETE CASCADE

);










