create table components(

    id int generated by default as  identity not null,

    name varchar(255) not null,
    price double precision not null,
    category VARCHAR(31) NOT NULL,

    primary key(id)
);

create table cpu(

    id int not null,

    socket varchar(50) not null ,
    power_consumption int not null,

    primary key (id),

    foreign key (id) references components(id) ON DELETE CASCADE

);

create table pc_case(

    id int not null,

    supported_form_factors varchar(50) not null,

    primary key (id),

    foreign key (id) references components(id) ON DELETE CASCADE

);

create table gpu(

    id int not null,

    power_consumption int not null,

    primary key (id),

    foreign key (id) references components(id) ON DELETE CASCADE

);


create table motherboard(

    id int not null,

    socket varchar(50) not null,
    form_factor varchar(50) not null,

    primary key (id),

    foreign key (id) references components(id) ON DELETE CASCADE

);

create table cooler(

    id int not null,

    supported_sockets varchar(50) not null,

    primary key (id),

    foreign key (id) references components(id) ON DELETE CASCADE

);

create table ram(

    id int not null,

    capacity int not null,
    speed int not null,

    primary key (id),

    foreign key (id) references components(id) ON DELETE CASCADE

);

create table psu(

    id int not null,

    wattage_capacity int not null,

    primary key (id),

    foreign key (id) references components(id) ON DELETE CASCADE

);










