create table build_pc(

    id int generated by default as identity not null,

    total_price double precision not null,

    status boolean default false,

    primary key (id)
);

create table build_components(

    build_id int not null ,
    component_id int not null,

    primary key (build_id,component_id),

    foreign key (build_id) references build_pc(id) ON DELETE CASCADE,
    foreign key (component_id) references components(id) ON DELETE CASCADE

);
